# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhenoDb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gene', models.CharField(max_length=20)),
                ('disease', models.CharField(max_length=150)),
            ],
        ),
    ]
